-- =========================================================
-- UNIGOV - Core Database Schema
-- Phase 1: Identity, Services & Workflow
-- =========================================================

-- =========================================================
-- 1. ROLES
-- =========================================================

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255)
);

-- =========================================================
-- 2. USERS
-- =========================================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20) UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id)
        REFERENCES roles(id),

    CONSTRAINT chk_users_status
        CHECK (status IN ('ACTIVE', 'BLOCKED'))
);

-- =========================================================
-- 3. CITIZEN PROFILES
-- =========================================================

CREATE TABLE citizen_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    date_of_birth DATE,
    address TEXT,
    district VARCHAR(100),
    state VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_citizen_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

-- =========================================================
-- 4. DEPARTMENTS
-- =========================================================

CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    code VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_department_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- =========================================================
-- 5. SERVICES
-- =========================================================

CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    code VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    department_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_service_department
        FOREIGN KEY (department_id)
        REFERENCES departments(id),

    CONSTRAINT chk_service_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- =========================================================
-- 6. WORKFLOW DEFINITIONS
-- =========================================================

CREATE TABLE workflow_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    service_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_workflow_service
        FOREIGN KEY (service_id)
        REFERENCES services(id),

    CONSTRAINT uq_workflow_service_version
        UNIQUE (service_id, version),

    CONSTRAINT chk_workflow_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- =========================================================
-- 7. WORKFLOW STEPS
-- =========================================================

CREATE TABLE workflow_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT NOT NULL,
    step_order INTEGER NOT NULL,
    name VARCHAR(200) NOT NULL,
    code VARCHAR(50) NOT NULL,
    department_id BIGINT,
    integration_required BOOLEAN NOT NULL DEFAULT FALSE,
    timeout_seconds INTEGER NOT NULL DEFAULT 30,
    retry_limit INTEGER NOT NULL DEFAULT 3,

    CONSTRAINT fk_step_workflow
        FOREIGN KEY (workflow_id)
        REFERENCES workflow_definitions(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_step_department
        FOREIGN KEY (department_id)
        REFERENCES departments(id),

    CONSTRAINT uq_workflow_step_order
        UNIQUE (workflow_id, step_order),

    CONSTRAINT uq_workflow_step_code
        UNIQUE (workflow_id, code),

    CONSTRAINT chk_step_order
        CHECK (step_order > 0),

    CONSTRAINT chk_timeout
        CHECK (timeout_seconds > 0),

    CONSTRAINT chk_retry_limit
        CHECK (retry_limit >= 0)
);

-- =========================================================
-- 8. APPLICATIONS
-- =========================================================

CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_number VARCHAR(50) NOT NULL UNIQUE,
    citizen_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    workflow_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
    current_step_order INTEGER,
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,

    CONSTRAINT fk_application_citizen
        FOREIGN KEY (citizen_id)
        REFERENCES users(id),

    CONSTRAINT fk_application_service
        FOREIGN KEY (service_id)
        REFERENCES services(id),

    CONSTRAINT fk_application_workflow
        FOREIGN KEY (workflow_id)
        REFERENCES workflow_definitions(id),

    CONSTRAINT chk_application_status
        CHECK (
            status IN (
                'DRAFT',
                'SUBMITTED',
                'IN_PROGRESS',
                'PENDING',
                'FAILED',
                'APPROVED',
                'REJECTED',
                'COMPLETED',
                'CANCELLED'
            )
        )
);

-- =========================================================
-- 9. APPLICATION STEPS
-- =========================================================

CREATE TABLE application_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    workflow_step_id BIGINT NOT NULL,
    step_order INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    error_message TEXT,
    retry_count INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT fk_app_step_application
        FOREIGN KEY (application_id)
        REFERENCES applications(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_app_step_workflow_step
        FOREIGN KEY (workflow_step_id)
        REFERENCES workflow_steps(id),

    CONSTRAINT uq_application_step_order
        UNIQUE (application_id, step_order),

    CONSTRAINT chk_application_step_status
        CHECK (
            status IN (
                'PENDING',
                'IN_PROGRESS',
                'COMPLETED',
                'FAILED',
                'SKIPPED'
            )
        ),

    CONSTRAINT chk_retry_count
        CHECK (retry_count >= 0)
);

-- =========================================================
-- INDEXES
-- =========================================================

CREATE INDEX idx_users_role
    ON users(role_id);

CREATE INDEX idx_services_department
    ON services(department_id);

CREATE INDEX idx_workflows_service
    ON workflow_definitions(service_id);

CREATE INDEX idx_workflow_steps_workflow
    ON workflow_steps(workflow_id);

CREATE INDEX idx_applications_citizen
    ON applications(citizen_id);

CREATE INDEX idx_applications_service
    ON applications(service_id);

CREATE INDEX idx_applications_status
    ON applications(status);

CREATE INDEX idx_application_steps_application
    ON application_steps(application_id);

CREATE INDEX idx_application_steps_status
    ON application_steps(status);
-- ============================================================
-- CONSENT MANAGEMENT
-- ============================================================

CREATE TABLE consents (
    id BIGSERIAL PRIMARY KEY,
    citizen_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    service_id BIGINT,
    purpose VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'GRANTED',
    granted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_consents_citizen
        FOREIGN KEY (citizen_id) REFERENCES users(id),

    CONSTRAINT fk_consents_department
        FOREIGN KEY (department_id) REFERENCES departments(id),

    CONSTRAINT fk_consents_service
        FOREIGN KEY (service_id) REFERENCES services(id),

    CONSTRAINT chk_consents_status
        CHECK (status IN ('GRANTED', 'REVOKED'))
);

CREATE INDEX idx_consents_citizen
    ON consents(citizen_id);

CREATE INDEX idx_consents_department
    ON consents(department_id);

CREATE INDEX idx_consents_status
    ON consents(status);


-- ============================================================
-- AUDIT LOGGING
-- ============================================================

CREATE TABLE audit_logs (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT,
    application_id BIGINT,
    department_id BIGINT,
    action VARCHAR(100) NOT NULL,
    resource_type VARCHAR(100),
    resource_id VARCHAR(100),
    status VARCHAR(20) NOT NULL,
    details TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_user
        FOREIGN KEY (user_id) REFERENCES users(id),

    CONSTRAINT fk_audit_application
        FOREIGN KEY (application_id) REFERENCES applications(id),

    CONSTRAINT fk_audit_department
        FOREIGN KEY (department_id) REFERENCES departments(id),

    CONSTRAINT chk_audit_status
        CHECK (status IN ('SUCCESS', 'FAILURE', 'INFO'))
);

CREATE INDEX idx_audit_user
    ON audit_logs(user_id);

CREATE INDEX idx_audit_application
    ON audit_logs(application_id);

CREATE INDEX idx_audit_department
    ON audit_logs(department_id);

CREATE INDEX idx_audit_action
    ON audit_logs(action);

CREATE INDEX idx_audit_created_at
    ON audit_logs(created_at);
